### ISSUE TITLE
No code at polybench link

### ISSUE THREAD

**Issue by bennn** [gpufpx/GPU-FPX-Benchmark#1]
Hi all,

The [FPXBench readme's section on Polybench](https://github.com/gpufpx/GPU-FPX-Benchmark/blob/main/Benchmarks/FPXBench/README.md#polybench) points to this [Ohio State page](http://web.cse.ohio-state.edu/~pouchet.2/software/polybench/GPU/index.html) for the benchmark suite. But the download link at the Ohio page doesn't work. Here's the broken link to the code. Changing to `~pouchet.2` doesn't work either.

<https://www.cse.ohio-state.edu/~pouchet/software/polybench/download/polybench-gpu-1.0.tar.gz>

Should the readme use this link (from Xinyi, thanks!) instead?

<https://github.com/sgrauerg/polybenchGpu>

Ben

**Comment by gpufpx** [comment]
Hi Ben, 
   Thank you! We've updated it! 
Best
